### ISSUE TITLE
Example data: typo

### ISSUE THREAD

**Issue by rmscheller** [LANDIS-II-Foundation/Extension-Biomass-Succession#14]
Brooke and Garry found a typo in the PRISM climate file such that the example doesn't run.

One of the standard deviations should be a variance.

**Comment by gsotnik** [comment]
There was also the following internal error: Could not load file or assembly 'Landis.Library.Climate, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

**Comment by bmarron18** [comment]
The climate data for the example included in Extension-Biomass-Succession (PRISM_data_AFRI_4.18.13.csv) was taken verbatim from Extension-NECN-Succession. These data were believed to be functionally correct. Great catch! Column 5 and Column 6 appear to be identical and clearly should not be. We will need to obtain a valid PRISM data file and update all of the examples that use weather data and the climate library. Interestingly, Extension-Biomass-Succession was recently run to reproduce another issue (PWL56c_QAQC&RepoStd-BiomassSuccession_20170512.txt) and the (typo-laden) weather data were apparently loaded correctly.  Garry, you may need to send us the details so that we can reproduce the error. Your scenario*.txt file would be a good start.

**Comment by gsotnik** [comment]
2017-05-16 08:20:01,792 - LANDIS-II 6.2 (beta release 1)
2017-05-16 08:20:01,807 - 
2017-05-16 08:20:02,275 - Loading scenario from file "scenario_s2e1.txt" ...
2017-05-16 08:20:02,369 - Initialized random number generator with seed = 1,070,967,728
2017-05-16 08:20:02,369 - Loading species data from file "./species_s2e1.txt" ...
2017-05-16 08:20:02,400 - Loading ecoregions from file "./ecoregions_s2e1.txt" ...
2017-05-16 08:20:02,431 - Initializing landscape from ecoregions map "./ecoregions_s2e1.gis" ...
2017-05-16 08:20:02,447 - Cell length = 100 m, cell area = 1 ha
2017-05-16 08:20:02,447 - Map dimensions: 99 rows by 99 columns = 9,801 cells
2017-05-16 08:20:02,463 - Sites: 9,801 active (100.0 %), 0 inactive (0.0 %)
2017-05-16 08:20:02,478 - Loading Biomass Succession extension ...
2017-05-16 08:20:02,509 -    Registering Data:  Succession.BiomassCohorts.
2017-05-16 08:20:02,509 -    Registering Data:  Succession.AgeCohorts.
2017-05-16 08:20:02,509 -    Registering Data:  Succession.WoodyDebris.
2017-05-16 08:20:02,509 -    Registering Data:  Succession.Litter.
2017-05-16 08:20:02,572 - Internal error occurred within the program:
2017-05-16 08:20:02,572 -   Could not load file or assembly 'Landis.Library.Climate, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
2017-05-16 08:20:02,572 - 
2017-05-16 08:20:02,572 - Stack trace:
2017-05-16 08:20:02,587 -    at Landis.Extension.Succession.Biomass.PlugIn.Initialize()
   at Landis.Model.Run(String scenarioPath, IUserInterface ui)
   at Landis.App.Main(String[] args)

**Comment by bmarron18** [comment]
Wow --weird just ran this. Let me have a look-see tonight. (May have sent
the wrong file to GitHub)

Thanks Garry!

B

Bruce Marron, MS
NSF IGERT Fellow
Earth, Environment, and Society PhD Program
School of the Environment
Portland State University

**Comment by bmarron18** [comment]
Just did a LANDIS-II run using Biomass Succession with "scenario_s2e1.txt" -- no problems. Sent you an email w/ the inputs/outputs from the entire run.

Not sure why you are not getting these results. LANDIS-II v. 6.1 installed? Latest version of Biomass Succession installed? My recommendation is that you uninstall Biomass Succession and re-install using the installer available in the GitHub repo (https://LANDIS-II-Foundation/Extension-Biomass-Succession/deploy/installer/LANDIS-II Biomass Succession 3.2-setup.exe)

**Comment by gsotnik** [comment]
2017-05-17 14:44:37,502 - LANDIS-II 6.2 (beta release 1)
2017-05-17 14:44:37,517 - 
2017-05-17 14:44:40,394 - Loading scenario from file "scenario_s2e1.txt" ...
2017-05-17 14:44:40,504 - Initialized random number generator with seed = 3,047,569,102
2017-05-17 14:44:40,504 - Loading species data from file "./species_s2e1.txt" ...
2017-05-17 14:44:40,535 - Loading ecoregions from file "./ecoregions_s2e1.txt" ...
2017-05-17 14:44:40,566 - Initializing landscape from ecoregions map "./ecoregions_s2e1.gis" ...
2017-05-17 14:44:40,598 - Cell length = 100 m, cell area = 1 ha
2017-05-17 14:44:40,629 - Map dimensions: 99 rows by 99 columns = 9,801 cells
2017-05-17 14:44:40,629 - Sites: 9,801 active (100.0 %), 0 inactive (0.0 %)
2017-05-17 14:44:40,645 - Loading Biomass Succession extension ...
2017-05-17 14:44:40,754 -    Registering Data:  Succession.BiomassCohorts.
2017-05-17 14:44:40,754 -    Registering Data:  Succession.AgeCohorts.
2017-05-17 14:44:40,754 -    Registering Data:  Succession.WoodyDebris.
2017-05-17 14:44:40,754 -    Registering Data:  Succession.Litter.
2017-05-17 14:44:40,910 - Internal error occurred within the program:
2017-05-17 14:44:40,910 -   Could not load file or assembly 'Landis.Library.Climate, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
2017-05-17 14:44:40,910 - 
2017-05-17 14:44:40,910 - Stack trace:
2017-05-17 14:44:40,926 -    at Landis.Extension.Succession.Biomass.PlugIn.Initialize()
   at Landis.Model.Run(String scenarioPath, IUserInterface ui)
   at Landis.App.Main(String[] args)
